version: "3"

services:
  frontend:
    image: nginx:alpine
    ports: 
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork

  nginx:
    image: nginx:alpine    
    networks: 
      - proxynetwork

  teste:
    image: nginx:alpine
    volumes:
      - ./nginx/teste.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork

networks: 
  proxynetwork:
    driver: bridge
      
  
  
  
  
  