version: "3"

services:

  proxy:
    image: leandroalves86/dc-sample-nginx:v1
    ports: 
      - 80:80
    networks: 
      - proxynetwork
    depends_on:
      - api

  api:
    image: leandroalves86/dc-sample-api:v1
    networks:
      - proxynetwork
    

networks: 
  proxynetwork:
    driver: bridge