version: "3"

services:
  proxy:
    image: nginx:alpine
    ports: 
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork

  teste1:
    image: nginx:alpine    
    volumes:
      - ./nginx/teste1.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork

  teste2:
    image: nginx:alpine
    volumes:
      - ./nginx/teste2.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork

  testeapi:
    image: node:alpine
    volumes:
      - ./api:/api
    working_dir: /api
    command: node program.js
    networks:
      - proxynetwork

networks: 
  proxynetwork:
    driver: bridge