version: "3"

services:
  proxy:
    image: nginx:alpine
    ports: 
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork
    depends_on:
      - api
      - animais
      - pessoas

  animais:
    image: nginx:alpine    
    volumes:
      - ./nginx/animais.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork
    depends_on:
      - api

  pessoas:
    image: nginx:alpine
    volumes:
      - ./nginx/pessoas.html:/usr/share/nginx/html/index.html
    networks: 
      - proxynetwork
    depends_on:
      - api

  api:
    image: node:alpine
    volumes:
      - ./api:/api
    working_dir: /api
    command: ash -c  "npm install && node program.js"
    networks:
      - proxynetwork
    

networks: 
  proxynetwork:
    driver: bridge